name: Build Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag cquinniv/hello-spring:$GITHUB_SHA
    - name: Push Docker image as SHA
      run: docker push cquinniv/hello-spring:$GITHUB_SHA
    - name: Tag image as latest
      run: docker tag cquinniv/hello-spring:$GITHUB_SHA cquinniv/hello-spring:latest
    - name: Push Docker image as latest
      run: docker push cquinniv/hello-spring:latest