name: Build Docker Image

on:
  push:
    branches: [ main ]

env:
  IMAGE_NAME: cquinniv/hello-node

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $IMAGE_NAME:$GITHUB_SHA
    - name: Push Docker image as SHA
      run: docker push $IMAGE_NAME:$GITHUB_SHA
    - name: Tag image as latest
      run: docker tag $IMAGE_NAME:$GITHUB_SHA $IMAGE_NAME:latest
    - name: Push Docker image as latest
      run: docker push $IMAGE_NAME:latest